DROP TABLE TB_TDS_CP5_FERRAMENTA CASCADE CONSTRAINTS;
DROP TABLE TB_TDS_CP5_USUARIO CASCADE CONSTRAINTS;

CREATE TABLE TB_TDS_CP5_USUARIO (
    ID_USUARIO           VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    EMAIL_USUARIO        VARCHAR2(190) NOT NULL UNIQUE,
    SENHA_USUARIO        VARCHAR2(100) NOT NULL,
    NOME_USUARIO         VARCHAR2(120) NOT NULL,
    TELEFONE_USUARIO     VARCHAR2(20),
    ROLE_USUARIO         VARCHAR2(40) DEFAULT 'ROLE_USER' NOT NULL,
    CREATED_AT           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE TB_TDS_CP5_FERRAMENTA (
    ID_FERRAMENTA            VARCHAR2(36) DEFAULT SYS_GUID() PRIMARY KEY,
    NOME_FERRAMENTA          VARCHAR2(50) NOT NULL,
    TIPO_FERRAMENTA          VARCHAR2(50) NOT NULL,
    CLASSIFICACAO_FERRAMENTA VARCHAR2(50) NOT NULL,
    TAMANHO_FERRAMENTA       NUMBER(10,2) NOT NULL,
    PRECO_FERRAMENTA         NUMBER(10,2) NOT NULL,
    ID_USUARIO               VARCHAR2(36) NOT NULL,
    CONSTRAINT FK_FERRAMENTA_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES TB_TDS_CP5_USUARIO (ID_USUARIO)
        ON DELETE CASCADE
);
